# Generated by Django 5.0.2 on 2024-03-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=96)),
                ('title', models.CharField(max_length=96)),
                ('listing_id', models.IntegerField()),
                ('bid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=96)),
                ('comment', models.CharField(max_length=256)),
                ('listing_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96)),
                ('desc', models.CharField(max_length=256)),
                ('seller', models.CharField(max_length=96)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('img_link', models.CharField(blank=True, default=None, max_length=300)),
            ],
        ),
    ]
