# Generated by Django 5.0.2 on 2024-03-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_category_listing_category_listing_isactive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
